UCLA scl 1.0
NumRows : 3
CoreRow Horizontal
  Coordinate : 0
  Height : 1
  Sitewidth : 1
  Sitespacing : 1
  Siteorient : N
  Sitesymmetry : Y
  SubrowOrigin : 0 NumSites : 20
End
CoreRow Horizontal
  Coordinate : 1
  Height : 1
  Sitewidth : 1
  Sitespacing : 1
  Siteorient : N
  Sitesymmetry : Y
  SubrowOrigin : 0 NumSites : 20
End
CoreRow Horizontal
  Coordinate : 2
  Height : 1
  Sitewidth : 1
  Sitespacing : 1
  Siteorient : N
  Sitesymmetry : Y
  SubrowOrigin : 0 NumSites : 20
End
