#include "placer/multilevel/Clusterer.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <stdexcept>

namespace placer
{
    namespace
    {
        struct PairScore { double neg_score; size_t a, b; bool operator<(const PairScore &o) const { if (neg_score != o.neg_score) return neg_score > o.neg_score; if (a != o.a) return a > o.a; return b > o.b; } };
        double groupArea(const Level &l, const std::vector<size_t> &g){ double a=0; for(auto i:g) a += l.objects[i].area(); return a; }
        std::pair<double,double> groupCenter(const Level &l, const std::vector<size_t> &g){ double a=groupArea(l,g), sx=0, sy=0; for(auto i:g){ double ar=l.objects[i].area(); sx+=ar*l.objects[i].cx(); sy+=ar*l.objects[i].cy(); } return {sx/std::max(EPS,a), sy/std::max(EPS,a)}; }
        void groupConnectivity(const Level &level, const std::vector<size_t> &group_of, int degree_cap, std::map<std::pair<size_t,size_t>,double> &conn, std::map<size_t,double> &ext)
        {
            for (const auto &net: level.nets){ std::vector<size_t> groups; std::set<size_t> seen; for(const auto&p:net.pins){ const auto&o=level.objects[p.object_id]; if(o.fixed||o.is_macro) continue; size_t g=group_of[p.object_id]; if(g!=std::numeric_limits<size_t>::max() && seen.insert(g).second) groups.push_back(g);} size_t d=groups.size(); if(!d) continue; for(auto g:groups) ext[g]+=1.0; if(d<2 || (int)d>degree_cap) continue; double w=1.0/std::max<size_t>(1,d-1); if(d<=16){ for(size_t i=0;i<d;i++) for(size_t j=i+1;j<d;j++){ auto a=std::minmax(groups[i],groups[j]); conn[a]+=w; } } else { std::sort(groups.begin(),groups.end()); auto hub=groups[0]; for(size_t j=1;j<d;j++) conn[{hub,groups[j]}]+=w; for(size_t j=0;j+1<d;j++) conn[{groups[j],groups[j+1]}]+=0.5*w; } }
        }
        std::vector<std::pair<size_t,size_t>> fallbackPairing(const std::vector<std::vector<size_t>> &groups, const Level&l, size_t needed){ std::vector<size_t> ord(groups.size()); std::iota(ord.begin(),ord.end(),0); std::sort(ord.begin(),ord.end(),[&](size_t a,size_t b){ auto ca=groupCenter(l,groups[a]), cb=groupCenter(l,groups[b]); double aa=groupArea(l,groups[a]), ab=groupArea(l,groups[b]); if(ca.first!=cb.first) return ca.first<cb.first; if(ca.second!=cb.second) return ca.second<cb.second; if(aa!=ab) return aa<ab; return l.objects[groups[a][0]].name < l.objects[groups[b][0]].name;}); std::vector<std::pair<size_t,size_t>> r; for(size_t k=0;k+1<ord.size() && r.size()<needed;k+=2) r.push_back({ord[k],ord[k+1]}); return r; }
        std::tuple<std::map<size_t,std::pair<double,double>>,double,double> shelfPack(const Level&l,const std::vector<size_t>&children,double target_width){ auto ordered=children; std::sort(ordered.begin(),ordered.end(),[&](size_t a,size_t b){ const auto&A=l.objects[a], &B=l.objects[b]; if(A.height!=B.height) return A.height>B.height; if(A.width!=B.width) return A.width>B.width; return A.name<B.name;}); double x=0,y=0,rowh=0,bw=0,bh=0; std::map<size_t,std::pair<double,double>> placed; for(auto child:ordered){ const auto&o=l.objects[child]; if(x>EPS && x+o.width>target_width+EPS){ y+=rowh; x=0; rowh=0;} placed[child]={x+0.5*o.width,y+0.5*o.height}; x+=o.width; rowh=std::max(rowh,o.height); bw=std::max(bw,x); bh=std::max(bh,y+rowh);} for(auto &kv:placed){ kv.second.first-=0.5*bw; kv.second.second-=0.5*bh;} return {placed,std::max(bw,EPS),std::max(bh,EPS)}; }
        std::tuple<std::map<size_t,std::pair<double,double>>,double,double> compactOffsets(const Level&l,const std::vector<size_t>&children){ if(children.size()==1){ auto&o=l.objects[children[0]]; return {{{children[0],{0,0}}},o.width,o.height}; } double area=0,maxw=0,sumw=0; for(auto i:children){ area+=l.objects[i].area(); maxw=std::max(maxw,l.objects[i].width); sumw+=l.objects[i].width;} double base=std::max(maxw,std::sqrt(std::max(area,EPS))); std::vector<double> cand={maxw,std::min(sumw,maxw+0.70*(base-maxw)),std::min(sumw,base),std::min(sumw,1.35*base),std::min(sumw,1.80*base)}; std::sort(cand.begin(),cand.end()); cand.erase(std::unique(cand.begin(),cand.end()),cand.end()); double best=std::numeric_limits<double>::infinity(), bw=0,bh=0; std::map<size_t,std::pair<double,double>> bo; for(double w:cand){ auto [off,pw,ph]=shelfPack(l,children,std::max(w,maxw)); double score=std::max(0.0,pw*ph-area)/std::max(area,EPS)+0.05*std::abs(std::log(std::max(pw,EPS)/std::max(ph,EPS))); if(score<best){best=score;bo=off;bw=pw;bh=ph;}} return {bo,bw,bh}; }
    }
    Level clusterOneLevel(const Level &fine, const ClusterConfig &cfg)
    {
        size_t target_movable = (size_t)std::max(1.0, std::ceil((double)fine.movableIds().size() / cfg.coarsen_ratio));
        return clusterOneLevel(fine, target_movable, cfg.degree_cap);
    }
    Level clusterOneLevel(const Level &fine, size_t target_movable, int degree_cap)
    {
        auto std_ids=fine.standardMovableIds(); auto macro_ids=fine.macroIds(); size_t desired_std=std::max<size_t>(1, target_movable>macro_ids.size()?target_movable-macro_ids.size():1);
        std::vector<std::vector<size_t>> groups; for(auto i:std_ids) groups.push_back({i});
        while(groups.size()>desired_std){ std::vector<size_t> group_of(fine.objects.size(),std::numeric_limits<size_t>::max()); for(size_t g=0;g<groups.size();++g) for(auto oid:groups[g]) group_of[oid]=g; std::map<std::pair<size_t,size_t>,double> conn; std::map<size_t,double> ext; groupConnectivity(fine,group_of,degree_cap,conn,ext); std::priority_queue<PairScore> pq; std::vector<double> areas; for(auto &g:groups) areas.push_back(groupArea(fine,g)); for(auto &kv:conn){ auto [a,b]=kv.first; double dij=kv.second; double da=std::max(EPS,ext[a]-dij), db=std::max(EPS,ext[b]-dij); double score=dij/(da*std::max(areas[a],EPS))+dij/(db*std::max(areas[b],EPS)); score/=1.0+std::abs(std::log(std::max(areas[a],EPS)/std::max(areas[b],EPS))); pq.push({-score,a,b}); } size_t need=groups.size()-desired_std; std::vector<std::pair<size_t,size_t>> selected; std::set<size_t> used; while(!pq.empty() && selected.size()<need){ auto p=pq.top(); pq.pop(); if(used.count(p.a)||used.count(p.b)) continue; used.insert(p.a); used.insert(p.b); selected.push_back({p.a,p.b}); } if(selected.size()<std::min(need,groups.size()/2)){ for(auto [a,b]:fallbackPairing(groups,fine,need-selected.size())) if(!used.count(a)&&!used.count(b)){used.insert(a);used.insert(b);selected.push_back({a,b}); if(selected.size()>=need) break;} } if(selected.empty()) break; std::map<size_t,size_t> mate; for(auto [a,b]:selected){mate[a]=b;mate[b]=a;} std::vector<std::vector<size_t>> ng; std::set<size_t> consumed; for(size_t gid=0;gid<groups.size();++gid){ if(consumed.count(gid)) continue; if(mate.count(gid)){ auto v=groups[gid]; v.insert(v.end(),groups[mate[gid]].begin(),groups[mate[gid]].end()); ng.push_back(v); consumed.insert(gid); consumed.insert(mate[gid]); } else { ng.push_back(groups[gid]); consumed.insert(gid);} } groups.swap(ng); }
        while(groups.size()>desired_std){ std::sort(groups.begin(),groups.end(),[&](auto&a,auto&b){return groupArea(fine,a)<groupArea(fine,b);}); auto a=groups.front(); groups.erase(groups.begin()); auto ac=groupCenter(fine,a); size_t best=0; double bd=std::numeric_limits<double>::infinity(); for(size_t k=0;k<groups.size();++k){auto c=groupCenter(fine,groups[k]); double d=(c.first-ac.first)*(c.first-ac.first)+(c.second-ac.second)*(c.second-ac.second); if(d<bd){bd=d;best=k;}} groups[best].insert(groups[best].end(),a.begin(),a.end()); }
        Level c; c.index=fine.index+1; c.fine_to_coarse=std::vector<size_t>(fine.objects.size(),std::numeric_limits<size_t>::max());
        auto make=[&](const std::vector<size_t>&children,const std::string&name,bool is_macro,bool fixed){ LObject obj; double phys=0, aw=0,sx=0,sy=0; for(auto i:children){ double a=fine.objects[i].area(); phys+=a; aw+=a; sx+=a*fine.objects[i].cx(); sy+=a*fine.objects[i].cy(); obj.members.insert(obj.members.end(),fine.objects[i].members.begin(),fine.objects[i].members.end()); } obj.name=name; obj.fixed=fixed; obj.is_macro=is_macro; obj.children=children; if(fixed){ const auto&o=fine.objects[children[0]]; obj.width=o.width; obj.height=o.height; obj.x=o.x; obj.y=o.y; obj.child_offsets[children[0]]={0,0}; } else if(children.size()==1 && is_macro){ const auto&o=fine.objects[children[0]]; obj.width=o.width; obj.height=o.height; obj.child_offsets[children[0]]={0,0}; obj.setCenter(sx/std::max(aw,EPS),sy/std::max(aw,EPS)); } else { auto [offs,pw,ph]=compactOffsets(fine,children); obj.child_offsets=offs; double aspect=std::min(4.0,std::max(0.25,pw/std::max(ph,EPS))); obj.width=std::sqrt(std::max(phys,EPS)*aspect); obj.height=std::max(phys,EPS)/std::max(obj.width,EPS); obj.setCenter(sx/std::max(aw,EPS),sy/std::max(aw,EPS)); Region pb{1e100,-1e100,1e100,-1e100}; for(auto ch:children){ auto off=obj.child_offsets[ch]; const auto&o=fine.objects[ch]; pb.xl=std::min(pb.xl,off.first-0.5*o.width); pb.xh=std::max(pb.xh,off.first+0.5*o.width); pb.yl=std::min(pb.yl,off.second-0.5*o.height); pb.yh=std::max(pb.yh,off.second+0.5*o.height);} obj.projection_bbox=pb; } size_t oid=c.objects.size(); for(auto ch:children)(*c.fine_to_coarse)[ch]=oid; c.objects.push_back(obj); };
        for(size_t k=0;k<groups.size();++k) make(groups[k],"cluster_L"+std::to_string(fine.index+1)+"_"+std::to_string(k),false,false); for(auto old:macro_ids) make({old},fine.objects[old].name,true,false); for(size_t old=0;old<fine.objects.size();++old) if(fine.objects[old].fixed) make({old},fine.objects[old].name,fine.objects[old].is_macro,true);
        for(const auto&n:fine.nets){ LNet cn{n.name,{}}; for(const auto&p:n.pins){ size_t cid=(*c.fine_to_coarse)[p.object_id]; if(cid>=c.objects.size()) throw std::runtime_error("invalid fine_to_coarse mapping"); auto it=c.objects[cid].child_offsets.find(p.object_id); double dx=0,dy=0; if(it!=c.objects[cid].child_offsets.end()){dx=it->second.first; dy=it->second.second;} cn.pins.push_back({cid,dx+p.offset_x,dy+p.offset_y}); } if(cn.pins.size()>=2) c.nets.push_back(cn); }
        return c;
    }
    std::vector<Level> buildHierarchy(const Level &l0, const ClusterConfig &cfg)
    { std::vector<Level> hs{l0}; size_t threshold=(size_t)cfg.current*(size_t)cfg.current; while(hs.back().movableIds().size()>threshold && (int)hs.size()<cfg.max_levels){ const Level&fine=hs.back(); size_t n=fine.movableIds().size(); size_t target=std::max(threshold,(size_t)std::ceil((double)n/cfg.coarsen_ratio)); auto t0=std::chrono::steady_clock::now(); std::cout<<"[cluster L"<<fine.index<<"] movable="<<n<<" target="<<target<<std::endl; Level coarse=clusterOneLevel(fine,target,cfg.degree_cap); size_t cm=coarse.movableIds().size(); double el=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count(); std::cout<<"[cluster L"<<fine.index<<"] result movable="<<cm<<" objects="<<coarse.objects.size()<<" nets="<<coarse.nets.size()<<" elapsed="<<el<<std::endl; if(cm>=n){ std::cout<<"[cluster] no reduction; stopping hierarchy"<<std::endl; break;} hs.push_back(std::move(coarse)); } return hs; }
}
