#include "placer/io/Reporter.hpp"
#include <fstream>
#include <iomanip>
namespace placer {
std::vector<std::string> historyFields(){return {"global_iteration","level","stage","iteration","lambda","raw_hpwl","raw_density_penalty","raw_objective","paper_ofr","wire_gradient_l1","density_gradient_l1","weighted_density_gradient_l1","total_gradient_l1","total_gradient_l2","beta_pr","direction_norm","s","bin_width","alpha","displacement_norm","overflow_bin_count","total_overflow","max_bin_overflow","maximum_bin_density","stage_best_objective","stage_best_iteration","is_stage_best","no_improve_count","projection_count","restart_due_to_zero_previous_norm","elapsed_sec"};}
static std::string esc(const std::string&s){std::string r="\"";for(char c:s){if(c=='\"'||c=='\\')r+='\\';r+=c;}return r+'\"';}
void writeHistoryCsv(const std::filesystem::path&p,const std::vector<HistoryRow>&h){std::ofstream f(p);auto fs=historyFields();for(size_t i=0;i<fs.size();++i)f<<(i?",":"")<<fs[i];f<<"\n"<<std::setprecision(17);for(const auto&r:h)f<<r.global_iteration<<','<<r.level<<','<<r.stage<<','<<r.iteration<<','<<r.lambda<<','<<r.raw_hpwl<<','<<r.raw_density_penalty<<','<<r.raw_objective<<','<<r.ofr<<','<<r.wire_gradient_l1<<','<<r.density_gradient_l1<<','<<r.weighted_density_gradient_l1<<','<<r.total_gradient_l1<<','<<r.total_gradient_l2<<','<<r.beta_pr<<','<<r.direction_norm<<','<<r.s<<','<<r.bin_width<<','<<r.alpha<<','<<r.displacement_norm<<','<<r.overflow_bin_count<<','<<r.total_overflow<<','<<r.max_bin_overflow<<','<<r.max_bin_utilization<<','<<r.stage_best_objective<<','<<r.stage_best_iteration<<','<<r.is_stage_best<<','<<r.no_improve_count<<','<<r.projection_count<<','<<r.restart_due_to_zero_previous_norm<<','<<r.elapsed_sec<<'\n';}
void writeHierarchyJson(const std::filesystem::path&p,const std::vector<Level>&hs){std::ofstream f(p);f<<"{\"levels\":[";for(size_t i=0;i<hs.size();++i){const auto&l=hs[i];size_t inc=0;for(const auto&n:l.nets)inc+=n.pins.size();f<<(i?",":"")<<"{\"index\":"<<l.index<<",\"objects\":"<<l.objects.size()<<",\"movable_objects\":"<<l.movableIds().size()<<",\"fixed_objects\":"<<l.objects.size()-l.movableIds().size()<<",\"active_nets\":"<<l.nets.size()<<",\"active_incidences\":"<<inc<<"}";}f<<"]}\n";}
void writeInterlevelJson(const std::filesystem::path&p,const std::vector<InterlevelHpwl>&v){std::ofstream f(p);f<<"[";for(size_t i=0;i<v.size();++i){const auto&r=v[i];f<<(i?",":"")<<"{\"coarse_hpwl\":"<<r.coarse_hpwl<<",\"fine_hpwl\":"<<r.fine_hpwl<<",\"delta\":"<<r.delta<<",\"relative_delta\":"<<r.relative_delta<<",\"coarse_nets\":"<<r.coarse_nets<<",\"fine_nets\":"<<r.fine_nets<<",\"paired_nets\":"<<r.paired_nets<<"}";}f<<"]\n";}
void writeSummaryJson(const std::filesystem::path&p,const std::vector<OptimizeResult>&rs,const Level&l,const PlacementDB&db,const Config&c,const OutputConsistency&oc){size_t fixed=0;for(const auto&x:db.cells)fixed+=x.fixed;std::ofstream f(p);f<<std::setprecision(17)<<"{\"benchmark_name\":"<<esc(c.aux.stem().string())<<",\"aux_path\":"<<esc(c.aux.string())<<",\"algorithm_mode\":\"paper_nonsmooth\",\"paper_objective\":\"W + lambda * P\",\"cell_count\":"<<db.cells.size()<<",\"movable_count\":"<<db.cells.size()-fixed<<",\"fixed_count\":"<<fixed<<",\"net_count\":"<<db.nets.size()<<",\"pin_count\":"<<db.pins.size()<<",\"target_density\":"<<c.target_density<<",\"random_seed\":"<<c.seed;if(!rs.empty())f<<",\"initial_hpwl\":"<<rs.front().initial_hpwl<<",\"initial_density_penalty\":"<<rs.front().initial_density_penalty<<",\"initial_ofr\":"<<rs.front().initial_ofr<<",\"final_hpwl\":"<<exactHpwl(l)<<",\"final_density_penalty\":"<<rs.back().density_penalty<<",\"final_ofr\":"<<rs.back().ofr_report;f<<",\"levels\":[";for(size_t i=0;i<rs.size();++i){const auto&r=rs[i];f<<(i?",":"")<<"{\"initial_hpwl\":"<<r.initial_hpwl<<",\"initial_ofr\":"<<r.initial_ofr<<",\"initial_lambda\":"<<r.initial_lambda<<",\"penalty_stage_count\":"<<r.stages.size()<<",\"total_iterations\":"<<r.history.size()<<",\"final_hpwl\":"<<r.hpwl<<",\"final_ofr\":"<<r.ofr_report<<",\"stop_reason\":"<<esc(r.stop_reason)<<"}";}f<<"],\"missing_external_components\":{\"white_space_allocation\":\"not_reproduced_from_available_paper\",\"look_ahead_legalization\":\"not_reproduced_from_available_paper\",\"legalization\":\"not_reproduced_from_available_paper\",\"detailed_placement\":\"not_reproduced_from_available_paper\"},\"output_consistency\":{\"solver_hpwl\":"<<oc.solver_hpwl<<",\"db_hpwl\":"<<oc.db_hpwl<<",\"reloaded_hpwl\":"<<oc.reloaded_hpwl<<",\"solver_density_penalty\":"<<oc.solver_density_penalty<<",\"db_density_penalty\":"<<oc.db_density_penalty<<",\"reloaded_density_penalty\":"<<oc.reloaded_density_penalty<<",\"solver_ofr\":"<<oc.solver_ofr<<",\"db_ofr\":"<<oc.db_ofr<<",\"reloaded_ofr\":"<<oc.reloaded_ofr<<",\"max_coordinate_difference\":"<<oc.max_coordinate_difference<<",\"consistent\":"<<(oc.consistent?"true":"false")<<"}}\n";}
void writeRunInfoJson(const std::filesystem::path&p,const Config&c,double e){std::ofstream f(p);f<<"{\"benchmark_name\":"<<esc(c.aux.stem().string())<<",\"aux\":"<<esc(c.aux.string())<<",\"out\":"<<esc(c.out.string())<<",\"elapsed_sec\":"<<e<<",\"pure_cpp\":true}\n";}
}
