#pragma once
#include "placer/objective/Objective.hpp"
#include "../TestSupport.hpp"
#include <cmath>
#include <limits>
#include <random>
#undef CHECK
#undef CHECK_EQ
#undef CHECK_NEAR
#define CHECK(condition) do { if (!(condition)) throw std::runtime_error("objective test CHECK failed: " #condition); } while(false)
#define CHECK_EQ(actual, expected) do { if (!((actual)==(expected))) throw std::runtime_error("objective test CHECK_EQ failed: " #actual); } while(false)
#define CHECK_NEAR(actual, expected, tolerance) do { if (std::abs((actual)-(expected))>(tolerance)) throw std::runtime_error("objective test CHECK_NEAR failed: " #actual); } while(false)

inline placer::Level objectiveLevel(bool nets=true){
 placer::Level l;l.index=4;
 l.objects={{"a",4,4,-1,2,false,false},{"b",4,4,5,2,false,false},{"fixed",4,4,2,6,true,true}};
 if(nets){l.nets.push_back({"ab",{{0,0,0},{1,0,0}}});l.nets.push_back({"af",{{0,0,0},{2,0,0}}});}
 return l;
}
inline placer::DensityGrid objectiveGrid(double target=.2){return placer::DensityGrid(placer::DensityConfig{{0,10,0,10},1,1,target});}
inline void checkIdentity(const placer::ObjectiveEvaluation&e,double tol=1e-10){CHECK_NEAR(e.objective,e.paper_l1_value+e.lambda*e.density_penalty,tol);for(size_t i=0;i<e.grad_x.size();++i){CHECK_NEAR(e.grad_x[i],e.wire_grad_x[i]+e.lambda*e.density_grad_x[i],tol);CHECK_NEAR(e.grad_y[i],e.wire_grad_y[i]+e.lambda*e.density_grad_y[i],tol);}}
inline void testValue(){auto l=objectiveLevel();auto g=objectiveGrid();for(double x:{0.,.25,1.,2.5,10.}){placer::ObjectiveEvaluator ev(3);auto e=ev.evaluate(l,g,x,placer::ObjectiveEvaluationMode::StatefulGradient);checkIdentity(e);CHECK_NEAR(e.exact_hpwl,e.paper_l1_value,1e-12);}}
inline void testWireOnly(){auto l=objectiveLevel();l.objects={{"a",1,1,1,1,false,false},{"b",1,1,8,8,false,false}};l.nets={placer::LNet{"n",{{0,0,0},{1,0,0}}}};placer::DensityGrid g(placer::DensityConfig{{0,10,0,10},1,1,1.});placer::ObjectiveEvaluator ev;auto e=ev.evaluate(l,g,7,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK_NEAR(e.density_penalty,0,0);CHECK_NEAR(e.objective,e.paper_l1_value,1e-12);for(size_t i=0;i<2;++i){CHECK_NEAR(e.grad_x[i],e.wire_grad_x[i],0);CHECK_NEAR(e.grad_y[i],e.wire_grad_y[i],0);}}
inline void testDensityOnly(){auto l=objectiveLevel(false);placer::ObjectiveEvaluator ev;auto e=ev.evaluate(l,objectiveGrid(),2,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK_NEAR(e.paper_l1_value,0,0);CHECK_NEAR(e.wire_grad_l1,0,0);CHECK_NEAR(e.objective,2*e.density_penalty,1e-12);checkIdentity(e);}
inline void testCombined(){auto l=objectiveLevel();placer::ObjectiveEvaluator ev;auto e=ev.evaluate(l,objectiveGrid(),.5,placer::ObjectiveEvaluationMode::StatefulGradient);checkIdentity(e);CHECK(e.wire_grad_l1>0);CHECK(e.density_grad_l1>0);}
inline void testOpposing(){auto l=objectiveLevel();placer::ObjectiveEvaluator ev;auto e=ev.evaluate(l,objectiveGrid(),1,placer::ObjectiveEvaluationMode::StatefulGradient);bool opposed=false;for(size_t i=0;i<l.objects.size();++i)if(e.wire_grad_x[i]*e.density_grad_x[i]<0||e.wire_grad_y[i]*e.density_grad_y[i]<0)opposed=true;CHECK(opposed);checkIdentity(e);}
inline void testLambda(){auto l=objectiveLevel();auto g=objectiveGrid();placer::ObjectiveEvaluator a,b;auto x=a.evaluate(l,g,.5,placer::ObjectiveEvaluationMode::StatefulGradient),y=b.evaluate(l,g,2,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK_NEAR(y.objective-x.objective,1.5*x.density_penalty,1e-10);for(size_t i=0;i<l.objects.size();++i)CHECK_NEAR(y.grad_x[i]-y.wire_grad_x[i],2*y.density_grad_x[i],1e-10);}
inline void testFixed(){auto l=objectiveLevel();placer::ObjectiveEvaluator ev;auto e=ev.evaluate(l,objectiveGrid(),1,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK(e.exact_hpwl>0);CHECK(e.density_penalty>0);CHECK(e.paper_ofr>0);CHECK_NEAR(e.wire_grad_x[2],0,0);CHECK_NEAR(e.density_grad_x[2],0,0);CHECK_NEAR(e.grad_x[2],0,0);CHECK_NEAR(e.grad_y[2],0,0);}
inline void testTieBoundary(){placer::Level l;l.index=9;l.objects={{"a",5,5,0,0,false,false},{"b",5,5,0,0,false,false},{"f",5,5,5,0,true,false}};l.nets={{"tie",{{0,0,0},{1,0,0}}}};placer::DensityGrid g(placer::DensityConfig{{0,10,0,10},2,1,.2});placer::ObjectiveEvaluator with_reports(19),direct(19);auto a=with_reports.evaluate(l,g,1,placer::ObjectiveEvaluationMode::StatefulGradient);(void)a;for(int i=0;i<3;++i)(void)with_reports.evaluate(l,g,1,placer::ObjectiveEvaluationMode::ValueOnly);auto x=with_reports.evaluate(l,g,1,placer::ObjectiveEvaluationMode::StatefulGradient);(void)direct.evaluate(l,g,1,placer::ObjectiveEvaluationMode::StatefulGradient);auto y=direct.evaluate(l,g,1,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK_EQ(x.wire_tie_count,y.wire_tie_count);for(size_t i=0;i<x.grad_x.size();++i){CHECK_NEAR(x.grad_x[i],y.grad_x[i],0);CHECK_NEAR(x.grad_y[i],y.grad_y[i],0);}checkIdentity(x);}
inline void testState(){testTieBoundary();}
inline void testReplay(){auto l=objectiveLevel();auto g=objectiveGrid();placer::ObjectiveEvaluator a(77),b(77);for(auto mode:{placer::ObjectiveEvaluationMode::StatefulGradient,placer::ObjectiveEvaluationMode::ValueOnly,placer::ObjectiveEvaluationMode::StatefulGradient}){auto x=a.evaluate(l,g,2,mode),y=b.evaluate(l,g,2,mode);CHECK_NEAR(x.objective,y.objective,0);CHECK_EQ(x.wire_tie_count,y.wire_tie_count);CHECK_EQ(x.grad_x.size(),y.grad_x.size());for(size_t i=0;i<x.grad_x.size();++i)CHECK_NEAR(x.grad_x[i],y.grad_x[i],0);}}
inline void testInvalid(){auto l=objectiveLevel();auto g=objectiveGrid();for(double x:{-1.,std::numeric_limits<double>::quiet_NaN(),std::numeric_limits<double>::infinity(),-std::numeric_limits<double>::infinity()}){bool threw=false;try{placer::ObjectiveEvaluator e;(void)e.evaluate(l,g,x,placer::ObjectiveEvaluationMode::ValueOnly);}catch(const std::runtime_error&e){threw=std::string(e.what()).find("objective evaluator")!=std::string::npos&&std::string(e.what()).find("lambda")!=std::string::npos;}CHECK(threw);}}
inline void testFiniteDifference(){auto l=objectiveLevel();l.objects[1].y=3.3;auto g=objectiveGrid();const double lambda=.3,h=1e-6;placer::ObjectiveEvaluator analytic;auto e=analytic.evaluate(l,g,lambda,placer::ObjectiveEvaluationMode::StatefulGradient);for(size_t oid:{0u,1u})for(int axis=0;axis<2;++axis){auto plus=l,minus=l;(axis?plus.objects[oid].y:plus.objects[oid].x)+=h;(axis?minus.objects[oid].y:minus.objects[oid].x)-=h;placer::ObjectiveEvaluator ep,em;double fp=ep.evaluate(plus,g,lambda,placer::ObjectiveEvaluationMode::ValueOnly).objective,fm=em.evaluate(minus,g,lambda,placer::ObjectiveEvaluationMode::ValueOnly).objective;CHECK_NEAR((fp-fm)/(2*h),axis?e.grad_y[oid]:e.grad_x[oid],1e-6);}}
inline void testDescent(){auto l=objectiveLevel();auto g=objectiveGrid();const double lambda=.01,alpha=1e-4;placer::ObjectiveEvaluator ev;auto before=ev.evaluate(l,g,lambda,placer::ObjectiveEvaluationMode::StatefulGradient);auto fixed=l.objects[2];for(size_t i=0;i<2;++i){l.objects[i].x-=alpha*before.grad_x[i];l.objects[i].y-=alpha*before.grad_y[i];}placer::ObjectiveEvaluator after_ev;auto after=after_ev.evaluate(l,g,lambda,placer::ObjectiveEvaluationMode::ValueOnly);CHECK(after.objective<before.objective);CHECK(after.exact_hpwl<before.exact_hpwl||after.paper_ofr<before.paper_ofr);CHECK(after.exact_hpwl<=before.exact_hpwl*1.001+1e-12);CHECK(after.paper_ofr<=before.paper_ofr*1.001+1e-12);CHECK_NEAR(l.objects[2].x,fixed.x,0);CHECK_NEAR(l.objects[2].y,fixed.y,0);}
inline void testCalls(){auto l=objectiveLevel();auto g=objectiveGrid();placer::ObjectiveEvaluator ev;for(int i=0;i<4;++i)(void)ev.evaluate(l,g,1,placer::ObjectiveEvaluationMode::ValueOnly);auto c=ev.callCounts();CHECK_EQ(c.value_evaluations,4u);CHECK_EQ(c.wire_state_commits,0u);CHECK_EQ(c.density_evaluations,4u);(void)ev.evaluate(l,g,1,placer::ObjectiveEvaluationMode::StatefulGradient);c=ev.callCounts();CHECK_EQ(c.stateful_evaluations,1u);CHECK_EQ(c.wire_state_commits,1u);CHECK_EQ(c.density_evaluations,5u);}
inline void testProperties(){std::mt19937 rng(5);for(int k=0;k<20;++k){auto l=objectiveLevel();l.objects[0].x=-1+.01*(rng()%50);double lambda=.1*(rng()%20);placer::ObjectiveEvaluator ev;auto a=ev.evaluate(l,objectiveGrid(),lambda,placer::ObjectiveEvaluationMode::StatefulGradient);CHECK(std::isfinite(a.objective));CHECK(a.objective+1e-12>=a.paper_l1_value);CHECK(a.density_penalty>=0);CHECK_EQ(a.grad_x.size(),l.objects.size());checkIdentity(a);}}
